modLoader="javafml" #mandatory
loaderVersion="[34,36)" #mandatory (28 is current forge version)
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/sokratis12GR/ArmorPlus/issues" #optional
[[mods]] #mandatory
modId="armorplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="ArmorPlus" #mandatory
updateJSONURL="https://raw.githubusercontent.com/sokratis12GR/ArmorPlus/1.16.5/armorplus-updater.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/armorplus" #optional
logoFile="headerimg.jpg"
credits="To everyone who helped with the translation of ArmorPlus: https://bit.ly/armorplus-credits" #optional
authors="SoFoDev" #optional
description='''
    ArmorPlus is a mod which introduces brand new multi-tiered arsenal to your Minecraft world, each with its own unique abilities so that they can all be utilized to the fullest depending on the different situations your journeys may encounter.
    It also adds some world generation to ensure that you will always have something new to explore.
'''
[[dependencies.armorplus]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,36)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.armorplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
# ArmorPlus
[[dependencies.armorplus]]
    modId="thedragonlib"
    mandatory=true
    versionRange="[1.16.3-1.1.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.armorplus]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"
